### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by hasshi1255** [hasshi1255/protospace-40757#1]
#URL
https://protospace-40757-1.onrender.com/

**Comment by shodai-ito** [comment]
@hasshi1255 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
一部のユーザー名が未編集のままとなっております。
該当のユーザー名が表示されるように実装しましょう！
<img width="619" alt="スクリーンショット 2024-07-31 15 37 21" src="https://github.com/user-attachments/assets/e47ac0ec-d943-4ced-a836-7365a0a0ace3">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by hasshi1255** [comment]
訂正いたしました。

**Comment by shodai-ito** [comment]
@hasshi1255 さん、再度ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
